### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by xaviml** [eloipuertas/ES2014B#107]
## Descripció

Com a Quality assurance he de testejar totes les issues completes fetes pel grup C en devel-C
## Temps estimades

8 hores 
## Objectius

Totes les issues creades amb el label: 'Group C', han de ser testejades i donar un feedback com a QA.
### Unity issues
- [x] #91 - Create an api to share features between characters, npcs,...
- [x] #93 - Programar escollir màgia
- [x] #99 - Programar millora de càmera
- [x] #100 - Programar menú pausa
##### Sprint 2 review
- [ ] #25 - Create HUD menu background
- [x] #26 - Create HUD lifebar
- [x] #27 - Create HUD manabar
- [ ] #28 - Create HUD bacpack menu and button
- [ ] #41 - Create door
- [ ] #68 - Creació del menu principal.
- [ ] #71 - Creació de menu character selection
- [ ] #82 - Create Potion
##### Sprint 3
- [x] #83 - mejora terreno para sprint3
- [ ] #87 - Creació game menu
- [ ] #109 - HUD Creació de les icones de habilitats
- [x] #113 - C-113-aturar musica ambient pause
- [x] #114 - C-114-so al passar sobre botons menus
- [ ] #115 - C-115-particules PJ
- [ ] #116 - C-116-ombres
- [ ] #117 - Colocar objetos destruibles por el jugador
- [ ] #118 - Create Container
- [x] #119 - Diseño definitivo escenario nivel1

**Comment by xaviml** [comment]
Totes les issues ja han rebut un feedback, tanco issue.
