### ISSUE TITLE
Test and validation issues of group A as QA

### ISSUE THREAD

**Issue by pherrusa7** [eloipuertas/ES2014B#120]
## Descripció

Com a Quality assurance he de testejar  i validar totes les issues del grup A.
## Temps estimat

8 hores 
## Objectius

Testejar i donar un feedback de totes les issues amb label 'Group A'.
## Issues
- [x] #106 Create Death Animation for Main Character
- [ ] #105 Create a Spell Cast Animation on the Main Character
- [x] #104 Create Animation Controller for Main Character
- [ ] #96 Vertex skinning for the Knight
- [ ] #95 Material and texture adding to the Knight 
- [ ] #94 Creation of a Knight model
- [x] #92 Programació pathfinder
- [x] #89 Create Idle Animation
- [x] #88 Create attack animation 
## Issues pendents
- [x] #70 Programar que el pj principal ataqui cos a cos
- [x] #39 Bug Incompatibility Blender Model with Mecanim [Unity] Animation
- [ ] #79 Add clothes to the model 
- [x] #14 Create walking animation on dummy main character
- [ ] #80 Creation of a weapon
- [x] #72 Integration group A

**Comment by pherrusa7** [comment]
Issues pendents: #105 #96 #95 #94  #79 #80
