### ISSUE TITLE
Validate issues completeness and test integrations

### ISSUE THREAD

**Issue by Mithrandir0x** [eloipuertas/ES2014B#124]
# Description

For each issue for `devel-B` branch, it is required to validate that the issue has been implemented correctly, and should be tested before deploying to `devel` branch.
## Tests
- [ ] The spider.
  - [ ] It has textures. #35
  - [x] It has `IDLE` animation. #102
  - [x] It looks to the player when is trying to kill her. #90
  - [x] It can create a path to follow the player. #92, #111, #112
  - [x] It can provide information about it's common statistics. #110, #91 
  - [x] The animations are performed better. #98 
- [ ] The troll.
  - [ ] It has a geometrical model. #86
  - [ ] It is rigged. #101
  - [ ] It has textures. #123
  - [ ] It has `WALK` animation. #103
