### ISSUE TITLE
Create walking animation on dummy main character

### ISSUE THREAD

**Issue by Payetus** [eloipuertas/ES2014B#14]
## Description

Creates a walking animation on the dummy object of issue #12. Communication with concept artist is essential for this issue.
## Objectius

Create animation for Main Caracter-
## Subtasks
- [x] #14 Create walking animation on dummy main character 10h
- [x] #13 Create arm animation on Dummy char  2.5h
- [x] #12 Adding Dummy main character 1h
- [x] #11 Create Dummy Scene 1h
## Estimated Time

Estimated time: 16 hours
## ProductBacklog

Moviment del Personatje personal

**Comment by Payetus** [comment]
This Issue is currenly blocked by bug #39

**Comment by Payetus** [comment]
Video of the animation
[![Video Link](http://content.screencast.com/users/CPayet/folders/Jing/media/d22a8efc-3e26-4340-b29c-edf675c8af5d/2014-10-29_1430.png)](http://screencast.com/t/gTiSiqWEP)
