### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by xaviml** [eloipuertas/ES2014B#141]
## Descripció

Com a Quality assurance he de testejar totes les issues completes fetes pel grup C en devel-C
## Temps estimades

8 hores 
## Objectius

Totes les issues creades amb el label: 'Group C', han de ser testejades i donar un feedback com a QA.
#### Sprint 3 review
- [x] #99 - Programar millora de càmera [@Folch]
#### Sprint 4
- [x] #125 - GameOver [@Folch]
- [x] #126 - Colocar al hud l'escut [@Folch]
- [x] #127 - Pausar joc [@Folch]
#### Sprint 3 review
- [ ] #25 - Create HUD menu background [@Roka0006] - invalid
- [ ] #28 - Create HUD bacpack menu and button [@Roka0006] - invalid
- [ ] #41 - Create door [@cctGitHub] - invalid
- [ ] #68 - Creació del menu principal [@Roka0006] - invalid
- [ ] #71 - Creació de menu character selection [@Roka0006] - invalid
- [ ] #82 - Create Potion [@xinsen] - invalid
- [ ] #87 - Creació game menu [@Roka0006] - invalid
- [ ] #109 - HUD Creació de les icones de habilitats [@Roka0006] - invalid
- [ ] #115 - C-115-particules PJ [@voriol] - aplazada
- [ ] #116 - C-116-ombres [@voriol] - aplazada
- [ ] #117 - Colocar objetos destruibles por el jugador [@cctGitHub] - aplazada
- [ ] #118 - Create Container [@xinsen] - invalid
#### Sprint 4
- [x] #3 - so al caminar personatge principal [@voriol] - (reopened)
- [x] #128 - Colocación pócimas en escenario [@cctGitHub]
- [x] #129 - Asignar ubicaciones en el escenario para las arañas [@cctGitHub]
- [x] #130 - C-130-modificar_llum_ambient [@voriol]
- [ ] #131 - C-131-efecte_so_magia [@voriol] - aplazada
- [ ] #136 - C-136-explosio_particules_impactar [@voriol] - aplazada
- [ ] #145 - Crear acceso nivel 2 [@cctGitHub]
- [x] #161 - Create new images for the main menu scene [@xavierfebrer]
- [x] #162 - Create new images for the select pj menu scene [@xavierfebrer]
- [x] #163 - Create new images for the gameplay (not paused, not gameover) [@xavierfebrer]
- [x] #167 - Colocación antorchas en terreno [@cctGitHub]
- [x] #168 - Modificar dimensiones de muros [@cctGitHub]
- [x] #169 - Create images for paused and gameover state [@xavierfebrer]
- [x] #170 - Add all the images (white) [@xavierfebrer]

**Comment by xaviml** [comment]
Tot correcte i amb el seu feedback corresponent. Tanco issue.
