### ISSUE TITLE
Test, validation  and integration issues of group A as QA

### ISSUE THREAD

**Issue by pherrusa7** [eloipuertas/ES2014B#149]
## Descripció

Com a Quality assurance he de testejar i validar totes les issues del grup A. Les issues que es tanquin seràn integrades a devel.
## Temps estimat

16 hores 
## Objectius

Testejar i donar un feedback de totes les issues amb label 'Group A'.
## Issues
- [x] #146 Programar llista items i interactuar amb l'entorn
- [ ] #147 Programar màgia NPC per la paral.lització del Personatge Principal
- [ ] #148 Programar que a l'atacar, el personatge principal es posi davant l'enemic
- [ ] #181 Creation of AnimationController for the knight model
- [x] #182 Integration of the model within the Unity project
- [ ] #183 Creation of an attack animation
## Issues pendents
- [ ] #106 Create Death Animation for Main Character
- [ ] #105 Create a Spell Cast Animation on the Main Character
- [x] #97 Weapon for the Knight
- [x] #96 Vertex skinning for the Knight
- [x] #95 Material and texture adding to the Knight 
- [x] #94 Creation of a Knight model
- [x] #79 Add clothes to the model 
- [x] #80 Creation of a weapon

**Comment by pherrusa7** [comment]
Issues pendents: #106 #105 #147 #148 #181 #183 
@Payetus: Dues issues pendents són teves i només els hi cal una descripció i condició d'acabament, ja que la issue en si, ja està integrada.
