### ISSUE TITLE
Validate issues completeness and test integrations

### ISSUE THREAD

**Issue by Mithrandir0x** [eloipuertas/ES2014B#171]
# Description

For each issue for `devel-B` branch, it is required to validate that the issue has been implemented correctly, and should be tested before deploying to `devel` branch.
## Tests
- Scenario thingies
  - [x] Create a door that can interact with the player. #158, #58, #176 
- Gameplay elements
  - [x] The spider can damage to other entities. #122, #157
  - [x] When the three spiders die, three new one will arise, and when each of them dies, a new one will spawn. #140
  - [x] It is possible to see an entity's life and mana bars over them. #151
- The spider
  - [x] It has `3` different textures. #35, #153, #159
  - [x] It has `ATTACK RECEIVED` animation. #132
  - [x] It has `DIE` animation. #133
  - [x] It has refined animations for `ATTACK` and `DIE` animations. #134, #135
  - [x] When damaged, it will execute `ATTACK RECEIVED` animation. #155
  - [x] When the player dies, the spiders won't still be following the player and bashing her thoroughly. #138
  - [x] It has a magic to snare the player from distance. #139, #156, #164, #165
  - [x] The spider does look at its target properly. #152
  - [x] When the spider attacks, it emit sounds. #166
- The troll
  - [x] It has a geometrical model. #86, #144, #159
  - [x] It is rigged. #101
  - [x] It has textures. #123, #144
  - [ ] It has `WALK` animation. #103
  - [x] It has a big damn mauler. #143
