### ISSUE TITLE
Create or change animation for the Knight Model

### ISSUE THREAD

**Issue by Payetus** [eloipuertas/ES2014B#186]
## Description

Refactor the animation for the female model so that i t fits the movement of the male model( The Knight). 
This issue will refactor the following animations:
- Walking Animation
- Idle Animation
- Basic Body to Body Attack animation.

Death animation will be left for another issue.
The Spell Cast Animation will not be refactored, but we will reuse it for the knight model.
## Objectives
- Create/Refactor Animation Controller
- Add the following states to the Knight Animation controller: Death, Walking, Idle, Attacking, Spell Casting. With their respective transitions and animations.
- Refactor Waling Animation
- Refactor Idle Animation
- Refactor Body to Body Attack Animation
## Subtasks
- [X] Create/Refactor Animation Controller
- [ ] Add the following states to the Knight Animation controller: Death, Walking, Idle, Attacking, Spell Casting. With their respective transitions and animations.
- [ ] Refactor Waling Animation
- [ ] Refactor Idle Animation
- [ ] Refactor Body to Body Attack Animation
## Estimated Time

Estimated time: 16 hours
## ProductBacklog

Personatje reb mal.

**Comment by pherrusa7** [comment]
@Payetus Falten descripcions! Sense descripcions la issue queda invàlida i sense milestone.

**Comment by pherrusa7** [comment]
@Payetus Tanco issue. Ja no es canviarà.
