### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by xaviml** [eloipuertas/ES2014B#188]
## Descripció

Com a Quality assurance he de testejar totes les issues completes fetes pel grup C en devel-C
## Temps estimades

8 hores 
## Objectius

Totes les issues creades amb el label: 'Group C', han de ser testejades i donar un feedback com a QA.
#### Sprint 5
- [x] #197 - Millorar càmera  [@Folch]
- [x] #225 - Escena dificultat [@Folch]
- [x] #226 - Millora del hud [@Folch]
#### Sprint 4 review
- [x] #54 - C-54-musica de combat en escenes de combat [@voriol]
- [x] #115 - C-115-particules PJ [@voriol]
- [x] #116 - C-116-ombres [@voriol]
- [ ] #117 - Colocar objetos destruibles por el jugador [@cctGitHub] - invalida
- [x] #131 - C-131-efecte_so_magia [@voriol]
- [x] #136 - C-136-explosio_particules_impactar [@voriol]
- [ ] #137 - C-137-particules_teranyina [@voriol] - duplicada per un altre grup
- [ ] #145 - Crear acceso nivel 2 [@cctGitHub] - duplicada per un altre grup
#### Sprint 5
- [x] #187 - mejora terreno [@cctGitHub]
- [x] #190 - Animate all the new textures added in Sprint 4 Menu [@xavierfebrer]
- [x] #191 - Animate all the new textures added in Sprint 4 SelectPJ [@xavierfebrer]
- [x] #192 - Animate all the new textures added in Sprint 4 Game Gameplay [@xavierfebrer]
- [x] #193 - Animate all the new textures added in Sprint 4 Game Pause [@xavierfebrer]
- [x] #194 - Animate all the new textures added in Sprint 4 Game Gameover/Win,... [@xavierfebrer]
- [x] #195 - Add animated healthmanabars over the npcs, add the border damage image [@xavierfebrer]
- [x] #196 - Add terrain textures to change the look and feel of the terrain [@xavierfebrer]
- [x] #198 - Crear escenario final juego [@cctGitHub]
- [x] #200 - C-200-particules_mossegada_aranya [@voriol]
- [x] #220 - Add easy, normal, hard difficulty textures with background [@xavierfebrer]
- [x] #221 - Create a background for the pause menu and the gameover menu [@xavierfebrer]
- [x] #227 - Perfeccionar escenario final juego [@cctGitHub]
- [x] #228 - Mejorar visibilidad de acceso discreto en nivel principal [@cctGitHub]
- [x] #236 - C-236-so botons dificultat [@voriol]
- [x] #237 - C-237-so you win [@voriol]
- [x] #238 - C-238-so ogre [@voriol]

**Comment by xaviml** [comment]
Tot testejat. Tanco issue
