### ISSUE TITLE
Test, validation and integration issues of group A as QA

### ISSUE THREAD

**Issue by pherrusa7** [eloipuertas/ES2014B#199]
## Descripció

Com a Quality assurance he de testejar i validar totes les issues del grup A. Les issues que es tanquin seràn integrades a devel.
## Temps estimat

16 hores 
## Objectius

Testejar i donar un feedback de totes les issues amb label 'Group A'.
## Ampliacions
- [x] #178 Poció
- [x] #241 Moure el Pj Principal mentres es prem el botó esquerra del mouse 
- [x] #234  Integration of animation controller for the amazon
- [x] #233 Create a idle animation for the knight
- [x] #232 Improve the idle animation of the amazona
- [x] #231 Creation of a magic animation for amazon and knight
- [x] #230 Creation of an attack animation
## Bugs
- [x] #175 Fallo de animación al andar
- [x] #177 Animació i só de caminar
- [x] #214 Distancia entre player y araña
- [x] #222 Poder atacar magia més freqüentment
- [x] #224 Rang de magia massa curt
- [x] #240 Threading bug
## Issues pendents
- [ ] #147 Programar màgia NPC per la paral.lització del Personatge Principal
- [x] #148 Programar que a l'atacar, el personatge principal es posi davant l'enemic
- [x] #181 Creation of AnimationController for the knight model
- [x] #183 Creation of an attack animation
- [x] #105 Create a Spell Cast Animation on the Main Character

**Comment by pherrusa7** [comment]
@aniskhoury @Demenus Bona feina nois!!! Tot enllestit!
