### ISSUE TITLE
Validate issues completeness and test integrations

### ISSUE THREAD

**Issue by Mithrandir0x** [eloipuertas/ES2014B#24]
# Description

For each issue for `devel-B` branch, it is required to validate that the issue has been implemented correctly, and should be tested before deploying to `devel` branch.
## Tests
- [ ] The spider model has been loaded correctly in the project.
  - [x] The spider has a geometric model. #21
  - [x] The spider is rigged so that it can be animated. #16
  - [x] The spider has the `WALK` animation. #17
  - [x] The spider has the `ATTACK` animation. #57 
  - [ ] The spider has a texture. #35, #36, #60 
  - [x] The spider has a reasonable geometrical complexity. #59 
- [x] The spider has life points, and it is possible to change them. #31
- [x] The spider can walk over the scenario and executes the `WALK` animation correctly. #22, #61, #62, #64 
- [x] The spider is able to follow the player, wherever she is. #32, #62
- [x] The spider is able to attack the player when she's near. #62, #74, #75, #85

**Comment by Mithrandir0x** [comment]
## Problems found during tests:
- Issues #35 and #36: The spider has no texture.
- Issue #22 and #32: The spider cannot walk over the scenario, and it cannot even follow a single thing. There's even an exception when executing the script:

![script_aimovement_exception](https://cloud.githubusercontent.com/assets/204448/4631080/be6f2c50-53b2-11e4-8821-61fd6bb2707a.PNG)

Issues #22, #32, #35 and #36 will be staged for the next sprint.

Oh, by the way! Next time I see an issue with no description, and no definition of "done", I kill you.

![achmed-the-dead-terrorist-jeff-dunham_small](https://cloud.githubusercontent.com/assets/204448/4631168/677ca00c-53b3-11e4-9433-334232ace110.jpg)

**Comment by Mithrandir0x** [comment]
Issue reopen as it will be moved to Sprint 2.

**Comment by Mithrandir0x** [comment]
Spider texturization will be moved to the next sprint.

**Comment by Mithrandir0x** [comment]
Reopening wrongly closed issue.

**Comment by Mithrandir0x** [comment]
Reclosing reopened rewrongly reissue. Yarrrr!
