### ISSUE TITLE
Test and validation issues of group A as QA

### ISSUE THREAD

**Issue by pherrusa7** [eloipuertas/ES2014B#37]
## Descripció

Com a Quality assurance he de testejar  i validar totes les issues del grup A.
## Temps estimat

8 hores 
## Objectius

Testejar i donar un feedback de totes les issues amb label 'Group A'.
## Issues
- [x] #20 Mover el personaje a una posición
- [x] #19 Obtener la posición del cursor
- [x] #15 Creation of a basic female shaped model
- [ ] #14 Create walking animation on dummy main character
- [ ] #13 Create arm animation on Dummy char 
- [ ] #12 Adding Dummy main character
- [ ] #11 Create Dummy Scene
- [ ] #4 QA: Integrar personatge principal

**Comment by pherrusa7** [comment]
## Estat al final del Sprint 1

Issues tancades: #15 #19 #20  
Issues obertes: #4 #11 #12 #13 #14  

## Comentaris

@aniskhoury @Demenus @Payetus Heu d'indicar les condicions de finalització, amb checkbox si és possible.
@Demenus @Payetus Com a dissenyador i animador heu de tenir tot rigorosament determinat per poder integrar les vostres parts i tancar les issues.
@Pherrusa7 Com a integrador, sub-dividir les tasques d'integració dels diferents membres del grup, per poder tancar issues realment completades.
