### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by xaviml** [eloipuertas/ES2014B#43]
## Descripció

Com a Quality assurance he de testejar totes les issues completes fetes pel grup C en devel-C
## Temps estimades

8 hores 
## Objectius

Totes les issues creades amb el label: 'Group C', han de ser testejades i donar un feedback com a QA.
### Unity issues
- [x] #40 - Reprogramar menu per reintegració sprint 1
- [x] #45 - Integrate Sprint 1 Review
- [x] #48 - Programar GameOver
- [x] #49 - Tornar al mainMenu amb ESC
- [x] #67 - Programar healthbar i manabar
##### Sprint 1 review
- [x] #3 - so al caminar personatge principal
- [ ] #25 - Create HUD menu background
- [ ] #26 - Create HUD lifebar
- [ ] #27 - Create HUD manabar
- [ ] #28 - Create HUD bacpack menu and button
##### Sprint 2
- [ ] #41 - Create door
- [x] #42 - Create Torch
- [x] #47 - Re-crear terreno del sprint 1
- [x] #50 - C-50-so al atacar mele PJ
- [x] #51 - C-51-so al atacar mele NPC
- [x] #52 - C-52-iluminar catacumba
- [x] #53 - C-53-so ambient catacumba 
- [x] #54 - C-54-musica de combat en escenes de combat
- [x] #55 - C-55-so i musica game over al morir PJ
- [x] #56 - C-56-so al morir NPC
- [x] #65 - Creación de columna y muro estilo medieval
- [x] #66 - Creación de estructura estilo catacumba
- [ ] #68 - Creació del menu principal. 
- [x] #69 - Construcción escenario lucha entre PP y NPC's
- [ ] #71 - Creació de menu character selection
- [ ] #81 - Creació menu create character
- [ ] #82 - Create Potion

**Comment by xaviml** [comment]
Tots aquelles issues que s'han quedat obertes, han estat pasades al sprint 3, en cada issue possa el motiu. @Roka0006 @xinsen
