### ISSUE TITLE
Test of the completes issues of group C as QA

### ISSUE THREAD

**Issue by xaviml** [eloipuertas/ES2014B#7]
## Descripció

Com a Quality assurance he de testejar totes les issues completes fetes pel grup C.
## Temps estimades

8 hores 
## Objectius

Totes les issues creades amb el label: 'Group C', han de ser testejades i donar un feedback com a QA.
## Issues per testejar
# Unity issues
- [x] #5 - Càmera que segueixi al personatge principal en tercera persona
- [x] #6 - Programació menú principal
- [x] #33 - Modificar Script menú
# Design issues
- [x] #1 - música durant el menu
- [x] #2 - llums base level 1 
- [ ] #3 - so al caminar personatge principal
- [x] #18 - Creating of terrain
- [ ] #25 - Create menu background
- [ ] #26 - Create lifebar
- [ ] #27 - Create manabar
- [ ] #28 - Create bacpack menu and button
- [x] #29 Create character menu and button
- [ ] #30 Creating object for the world

**Comment by xaviml** [comment]
Cierro issue. Razones por las que las dejo abiertas algunas:
- #3 @voriol - Como no tenemos personaje principal, no puedo testearlo, aplazamos este issue para al segundo sprint
- #25, #26, #27, #28 @Roka0006 - La condición de finalización no es explícita. A más la lifebar y el manabar deben aparecer en el HUD. También aplazamos estas 4 issues para el segundo sprint.
- #30 @xinsen - La condición de finalización no es explícita. No puedo testearlo. Aplazamos esta issue para el segundo sprint.

Recordad de poner una condición de finalización bien explicada!
