### ISSUE TITLE
Test and validation issues of group A as QA

### ISSUE THREAD

**Issue by pherrusa7** [eloipuertas/ES2014B#73]
## Descripció

Com a Quality assurance he de testejar  i validar totes les issues del grup A.
## Temps estimat

8 hores 
## Objectius

Testejar i donar un feedback de totes les issues amb label 'Group A'.
## Issues
- [ ] #70 Programar que el pj principal ataqui cos a cos
- [ ] #39 Bug Incompatibility Blender Model with Mecanim [Unity] Animation
- [x] #76 Add materials to the main character model 
- [x] #77 Add face and hair to the main model
- [x] #78 Add vertex skinning to the model
- [ ] #79 Add clothes to the model 
- [ ] #80 Creation of a weapon
- [x] #72 Integration group A
## Issues pendents
- [ ] #14 Create walking animation on dummy main character
- [x] #13 Create arm animation on Dummy char 
- [x] #12 Adding Dummy main character
- [x] #11 Create Dummy Scene

**Comment by pherrusa7** [comment]
#11, #12, #13 Són subtasques de #14 i no haurien de ser issues, per tant, són etiquetades com 'invalid' i són tancades.
